src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>External Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA Latest Data/main/default/objects/Trade_Ally_Project__c/Trade_Ally_Project__c.object-meta.xml
<CustomObject>
    <label>Trade Ally Project</label>
    <nameField>
        <displayFormat>TAPN-{0000}</displayFormat>
        <label>Trade Ally Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA Latest Data/main/default/objects/Trade_Ally_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Trade Ally Projects</relationshipLabel>
    <relationshipName>Trade_Ally_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA Latest Data/main/default/objects/Trade_Ally_Project__c/fields/Trade_Ally__c.field-meta.xml
<CustomField>
    <fullName>Trade_Ally__c</fullName>
    <label>Trade Ally</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trade Ally Projects</relationshipLabel>
    <relationshipName>Trade_Ally_Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/force-app/main/default/classes/ProjectTriggerHandler.cls
public class ProjectTriggerHandler {
    public static void createTAProjectJunctions(Map<Id, List<String>> projectIdPartnersMap, List<String> partnerIdList) {
        List<Trade_Ally_Project__c> listTAProjects = new List<Trade_Ally_Project__c>();
        List<Account> tradeAllyAccounts = [SELECT Id, External_Id__c FROM Account WHERE
                                           External_Id__c IN: partnerIdList];
        for(Account a: tradeAllyAccounts) {
            for(Id projectId : projectIdPartnersMap.keySet()) {
                List<String> partnerListFromMap = projectIdPartnersMap.get(projectId);
                if(partnerListFromMap.contains(a.External_Id__c)) {
                    Trade_Ally_Project__c tap = new Trade_Ally_Project__c();
                    tap.Project__c = projectId;
                    tap.Trade_Ally__c = a.Id;
                    /*Account a = new Account(External_Id__c=s);
					tap.Trade_Ally__r = a;*/
                    listTAProjects.add(tap);
                }
            }
        }
        insert listTAProjects;
    }
    
    public static void updateTAProjectJunctions(Map<Id, List<String>> projectIdPartnersMap, List<String> partnerIdList, List<Id> projectIdDeleteList) {
    	List<Trade_Ally_Project__c> objectsToDelete = [SELECT Id FROM Trade_Ally_Project__c WHERE Project__c IN: projectIdDeleteList];
        if(!objectsToDelete.isEmpty()){
            Database.Delete(objectsToDelete, false);
        }
        ProjectTriggerHandler.createTAProjectJunctions(projectIdPartnersMap, partnerIdList);
    }
}