src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Design-Build Firm</fullName>
                </value>
                <value>
                    <fullName>Distribution / Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Energy Managment / DR</fullName>
                </value>
                <value>
                    <fullName>Engineering Services</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Contract Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Projects_Completed__c</fullName>
        <label>Projects Completed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Search_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Contractor can be searched in Find Trade Ally.</description>
        <label>Search Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tier_Level__c</fullName>
        <label>Tier Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Special</fullName>
                    <label>Premium</label>
                </value>
                <value>
                    <fullName>Common</fullName>
                    <label>Regular</label>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Demographic__c.object
<CustomObject>
    <fields>
        <fullName>Languages_spoken_other_than_English__c</fullName>
        <label>Languages spoken other than English</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Vietnamese</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Demographics</relationshipLabel>
        <relationshipName>Demographics</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Demographic</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demographic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demographics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SingleFilterInfoWrapper__c.object
<CustomObject>
    <fields>
        <fullName>Filter_Name__c</fullName>
        <label>Filter Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value_String__c</fullName>
        <label>Value String</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>SingleFilterInfoWrapper</label>
    <nameField>
        <displayFormat>N-{00000}</displayFormat>
        <label>SingleFilterInfoWrapper Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SingleFilterInfoWrappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Specialty__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Territory_Type__c</fullName>
        <label>Territory Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>County</fullName>
                </value>
                <value>
                    <fullName>City</fullName>
                </value>
                <value>
                    <fullName>Zip Code</fullName>
                </value>
                <value>
                    <fullName>Municipality</fullName>
                    <isActive>false</isActive>
                    <label>Municipality</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Territory_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Assigned Trade Allies</relationshipLabel>
        <relationshipName>Territory_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <label>Trade Ally</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Trade Ally</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Trade Ally</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Territory Assignments</relationshipLabel>
        <relationshipName>Territory_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Territory Assignment</label>
    <nameField>
        <displayFormat>TAN-{000000}</displayFormat>
        <label>Territory Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Specialty__c.object
<CustomObject>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Participating Programs</label>
        <referenceTo>Specialty__c</referenceTo>
        <relationshipLabel>Trade Ally Specialties</relationshipLabel>
        <relationshipName>Trade_Ally_Specialties</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <label>Trade Ally</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a Trade Ally.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Trade Ally</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trade Ally Specialties</relationshipLabel>
        <relationshipName>Trade_Ally_Specialties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trade Ally Specialty</label>
    <nameField>
        <displayFormat>TAS-{000000}</displayFormat>
        <label>Trade Ally Specialty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Specialties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA Latest Data/main/default/classes/FindTARest.cls
@RestResource(urlMapping = '/FindTA/*')
global with sharing class FindTARest {

	public static final String QUERY_PARAM_ID = 'id';
	public static final String QUERY_PARAM_NAME = 'name';
	public static final String QUERY_PARAM_SECTOR = 'sector';
	public static final String QUERY_PARAM_SPECIALTIES = 'specialties';
	public static final String QUERY_PARAM_BUSINESS_TYPE = 'type';
	public static final String QUERY_PARAM_TIER = 'tier';
	public static final String QUERY_PARAM_CONTRACTED = 'contracted';

	/**
	 * Allowed combinations of parameters:
	 * 1. No parameter at all
	 * 2. sector and specialties must NOT be empty, others are optional
	 */
	@HttpGet
	global static void searchTradeAllies() {
        //Get request query parameters
		RestRequest req = RestContext.request;
		String taId = req.params.get(QUERY_PARAM_ID);
		String companyName = req.params.get(QUERY_PARAM_NAME);
        String address = req.params.get('address');
		String sector = req.params.get(QUERY_PARAM_SECTOR);
		String businessTypes = req.params.get(QUERY_PARAM_BUSINESS_TYPE);
		String latitude = req.params.get('latitude');
		String longitude = req.params.get('longitude');
		String specialties = req.params.get(QUERY_PARAM_SPECIALTIES);
		String participatingStates = req.params.get('territories');
		String radius = req.params.get('radius');
		String tier = req.params.get(QUERY_PARAM_TIER) == 'true' ? 'Special' : '';
		Boolean contractSigned = req.params.get(QUERY_PARAM_CONTRACTED) == 'true' ? true : false;
        //Audit wrapper
		SearchRequestWrapper wrapper = new SearchRequestWrapper();
        List<SingleFilterInfoWrapper__c> filterList = new List<SingleFilterInfoWrapper__c>();
        //Construct query and populate audit wrapper
		String query = constructQuery
		(taId, radius, companyName, sector, businessTypes, latitude, longitude, specialties, participatingStates, tier, contractSigned, filterList);
		wrapper.listOfFilters = filterList;
        List<Account> result = null;
        if(query != null) {
			result = Database.query(query);
        }
        //System.debug(String.valueOf(result));
        RestContext.response.addHeader('Content-Type', 'application/json');
    	RestContext.response.responseBody = Blob.valueOf(JSON.serializePretty(result));
    	//return result;
	}      

	private static String constructQuery(String taId, String radius, String companyName, String sector, String businessTypes, String latitude, String longitude, String specialties, String participatingStates, String tier, Boolean contractSigned, List<SingleFilterInfoWrapper__c> filterList) {
        Boolean specialtyRequested = false;
        Boolean stateRequested = false;
        List<String> accountIds = new List<String>();
        List<String> accountIdsStates = new List<String>();
        List<String> accountIdsSpecialties = new List<String>();
        if(specialties != null && specialties.length()> 0) {
            specialtyRequested = true;
            Set<String> accountIdSet = getSpecialtyAccountIds(specialties, sector, filterList);
            accountIdsSpecialties.addAll(accountIdSet);
            if(accountIdsSpecialties.size() == 0) {
                  //This means that the user sent in specialties in the params list, but nothing matching those values was found
                  //In this case, we don't need to query for anything else
                  return null;
            }
        }
        if(participatingStates != null && participatingStates.length()> 0) {
            stateRequested = true;
            Set<String> accountIdSet = getStatesAccountIds(participatingStates, filterList);
            accountIdsStates.addAll(accountIdSet);
            if(accountIdsStates.size() == 0) {
                //This means that the user sent in states in the params list, but nothing matching those values was found
                //In this case, we don't need to query for anything else
                return null;
        	}
        }
        if(specialtyRequested && stateRequested)
        	accountIds.addAll(intersect(accountIdsStates, accountIdsSpecialties));
        else if(specialtyRequested && !stateRequested)
            accountIds.addAll(accountIdsSpecialties);
        else if(!specialtyRequested && stateRequested)
            accountIds.addAll(accountIdsStates);
        
        Boolean whereConditionAdded = false;
				String query = 'SELECT Id, Name, Tier_Level__c, Contract_Signed__c, Projects_Completed__c, Rating, Business_Type__c, BillingLatitude, BillingLongitude, Phone, Website, BillingStreet, BillingCity, BillingState, BillingPostalCode, (Select name, email, phone from Contacts), (Select Specialty__r.Name, Specialty__r.Sector__c from Trade_Ally_Specialties__r), (Select Territory__r.Name, Territory__r.Territory_Type__c from Territory_Assignments__r), (Select Demographic__c.id, Demographic__c.Languages_spoken_other_than_English__c from Demographics__r) FROM Account ';
        if (latitude != null && latitude.length() > 0) {
            addFilterToList('latitude', latitude, filterList);
			if (longitude != null && longitude.length() > 0) {
                addFilterToList('longitude', longitude, filterList);
                System.debug('radius: '+radius);
                if(radius != null && radius.length() > 0) {
                    addFilterToList('radius', radius, filterList);
					query = query + 'WHERE DISTANCE(BillingAddress, GEOLOCATION(' + Decimal.valueOf(latitude) + ',' + Decimal.valueOf(longitude) + '), \'mi\') < '+ Decimal.valueOf(radius);
					whereConditionAdded = true;
                }
			}
		}

		if (taId != null && taId.length() > 0) {
			addFilterToList('taId', taId, filterList);
			if (whereConditionAdded) {
				query = query + ' AND ';
			} else {
				query = query + ' WHERE ';
				whereConditionAdded = true;
			}
			query = query + ' Id = :taId';
		}

		if (companyName != null && companyName.length() > 0) {
            addFilterToList('companyName', companyName, filterList);
			if (whereConditionAdded)
			query = query + ' AND ';
			else {
				query = query + ' WHERE ';
				whereConditionAdded = true;
			}
			query = query + 'Name = :companyName';
		}
		if (businessTypes != null && businessTypes.length()> 0) {
            addFilterToList('businessTypes', businessTypes, filterList);
			businessTypes = String.escapesinglequotes(businessTypes);
			List<String> businessTypeList = businessTypes.split(',');
			if (whereConditionAdded)
			query = query + ' AND ';
			else {
				query = query + ' WHERE ';
				whereConditionAdded = true;
			}
			query = query + 'Business_Type__c INCLUDES (';
			for (integer i = 0; i<businessTypeList.size(); i++) {
				query = query + '\'' + businessTypeList[i] + '\'';
				if (i != businessTypeList.size() - 1)
				query = query + ',';
			}
			query = query + ')';
		}
        //Check for enable contractor search box
        if (whereConditionAdded)
			query = query + ' AND Search_Enabled__c = true';
		else {
			query = query + ' WHERE Search_Enabled__c = true';
			whereConditionAdded = true;
		}

		//Check for premium tier 
		if (tier == 'Special') {
			if (whereConditionAdded) {
				query = query + ' AND Tier_Level__c = \'Special\'';
			} else {
				query = query + ' WHERE Tier_Level__c = \'Special\'';
				whereConditionAdded = true;
			}
		}

		// Check for contract signed
		if (contractSigned) {
			if (whereConditionAdded) {
				query = query + ' AND Contract_Signed__c = true';
			} else {
				query = query + ' WHERE Contract_Signed__c = true';
				whereConditionAdded = true;
			}
		}

        //Check for the record type of TA
        if (whereConditionAdded)
			query = query + ' AND RecordType.Name = \'Trade Ally\'';
		else {
			query = query + ' WHERE RecordType.Name =\'Trade Ally\'';
			whereConditionAdded = true;
		}
		if(accountIds.size() > 0) {
			if (whereConditionAdded)
			query = query + ' AND ';
			else {
				query = query + ' WHERE ';
				whereConditionAdded = true;
			}
			query = query + 'ID IN (';
			for (integer i = 0; i < accountIds.size(); i++) {
				query = query + '\'' + accountIds[i] + '\'';
				if (i != accountIds.size() - 1)
				query = query + ',';
			}
			query = query + ')';
		}
		System.debug('query '+query);
		return query;
	}
    
    private static Set<String> getSpecialtyAccountIds(String specialties, String sector, List<SingleFilterInfoWrapper__c> filterList) {
        Set<String> accountIdSet = new Set<String>();
        System.debug('specialties '+specialties);
        if (specialties != null && specialties.length()> 0 && sector != null && sector.length() > 0) {
            addFilterToList('specialties', specialties, filterList);
			specialties = String.escapesinglequotes(specialties);
			List<String> specialtyList = specialties.split(',');
			List<String> sectorList = sector.split(',');
			String queryForId = 'SELECT Trade_Ally__c from Trade_Ally_Specialty__c where Specialty__r.Name IN (';
			for (integer i = 0; i<specialtyList.size(); i++) {
				queryForId = queryForId + '\'' + specialtyList[i] + '\'';
				if (i != specialtyList.size() - 1)
				queryForId = queryForId + ',';
			}
			queryForId = queryForId + ')';

			queryForId = queryForId + ' AND Specialty__r.Sector__c IN (';
			for (integer i = 0; i<sectorList.size(); i++) {
				queryForId = queryForId + '\'' + sectorList[i] + '\'';
				if (i != sectorList.size() - 1)
					queryForId = queryForId + ',';
			}
			queryForId = queryForId + ')';
			System.debug('[getSpecialtyAccountIds] queryForId = ' + queryForId);
			List<sObject> result = Database.query(queryForId);
			for(SObject s:result) {
				accountIdSet.add(String.valueOf(s.get('Trade_Ally__c')));
			}
		}
        return accountIdSet;
    }
    
    private static Set<String> getStatesAccountIds(String participatingStates, List<SingleFilterInfoWrapper__c> filterList) {
        Set<String> accountIdSet = new Set<String>();
        System.debug('participatingStates '+participatingStates);
		if (participatingStates != null && participatingStates.length()> 0) {
            addFilterToList('participatingStates', participatingStates, filterList);
			participatingStates = String.escapesinglequotes(participatingStates);
			List<String> stateList = participatingStates.split(',');
			// YH (2019-03-15): FTA sends Territory__r.Id 
			String queryForId = 'SELECT Trade_Ally__c FROM Territory_Assignment__c where Territory__r.Id IN (';
			for (integer i = 0; i<stateList.size(); i++) {
				queryForId = queryForId + '\'' + stateList[i] + '\'';
				if (i != stateList.size() - 1)
				queryForId = queryForId + ',';
			}
			queryForId = queryForId + ')';
			List<sObject> result = Database.query(queryForId);
			for(SObject s:result) {
				accountIdSet.add(String.valueOf(s.get('Trade_Ally__c')));
			}
		}
        return accountIdSet;
    }
    
    private static void addFilterToList(String filterName, String filterValue, List<SingleFilterInfoWrapper__c> filterList) {
        	SingleFilterInfoWrapper__c singleFilter = new SingleFilterInfoWrapper__c();
            singleFilter.Filter_Name__c = filterName;
            singleFilter.Value_String__c = filterValue;
            filterList.add(singleFilter);
    }
    
    private static List<String> intersect(List<String> listA, List<String> listB) {
        List<String> resultList = new List<String>();
        for(String str : listA) {
            if(listB.contains(str)) {
                resultList.add(str);
            }
        }
        return resultList;
    }
}