src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Business_Types__c</fullName>
        <label>Application Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Trade_Service_Pro</fullName>
                    <label>Trade Service Pro</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_and_Conditions__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Terms_and_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <label>Application Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Trade_Service_Pro</fullName>
                    <label>Trade Service Pro</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <label>Text</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <label>Terms and Conditions</label>
    <nameField>
        <displayFormat>TCV-{000000}</displayFormat>
        <label>Terms and Conditions Version</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms and Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CopyTermsAndConditionsTest.cls
@IsTest
private class CopyTermsAndConditionsTest {
	@IsTest
	static void testBehavior() {
		Account newAccount = new Account(
				Name = 'newAccount'
		);
		insert newAccount;
		Application__c newApplication = new Application__c(
				Trade_Ally__c = newAccount.Id,
            	Business_Types__c = 'Contractor'
		);
		insert newApplication;
		List<Application__c> applications = [
				SELECT Id
				FROM Application__c
		];
		System.assert(applications != null);
	}

	@IsTest
	static void testBehaviorWithActiveRecords() {
		Account newAccount = new Account(
				Name = 'newAccount'
		);
		insert newAccount;
		Application__c newApplication = new Application__c(
				Trade_Ally__c = newAccount.Id,
            	Business_Types__c = 'Contractor'
		);
		Terms_and_Conditions__c newConditions = new Terms_and_Conditions__c(
				Active__c = true,
				Text__c = 'text',
            	Application_Type__c = 'Contractor'
		);
		insert newConditions;
		insert newApplication;
		List<Application__c> applications = [
				SELECT Id
				FROM Application__c
		];
		System.assert(applications != null);
	}

	@IsTest
	static void testBehaviorNoApplicationType() {
		Account newAccount = new Account(
				Name = 'newAccount'
		);
		insert newAccount;
		Application__c newApplication = new Application__c(
				Trade_Ally__c = newAccount.Id
		);
		Terms_and_Conditions__c newConditions = new Terms_and_Conditions__c(
				Active__c = true,
				Text__c = 'text'
		);
		insert newConditions;
		insert newApplication;
		List<Application__c> applications = [
				SELECT Id
				FROM Application__c
		];
		System.assert(applications != null);
	}
}