src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>External Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Trade_Ally_Event__c</fullName>
        <label>Trade Ally Event</label>
        <referenceTo>Trade_Ally_Event__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EAN-  {000000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee_Contact__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendee Contacts</relationshipLabel>
    <relationshipName>Attendee_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Trade_Ally_Event__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Trade Ally Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Ally Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TradeAllyEventsControllerTest.cls
@IsTest
private class TradeAllyEventsControllerTest {
	@TestSetup
	static void setupTest() {
        // Create an account
        Account acct = new Account(Name='Test Account');
        acct.external_Id__c = '1';
        insert acct;
        // Create a contact
        Contact contact = new Contact();
        contact.Firstname ='first';
        contact.Lastname ='last';
        contact.Level__c = 'Primary';
        contact.AccountId = acct.id;
        insert contact;
		Trade_Ally_Event__c newEvent = new Trade_Ally_Event__c();
		newEvent.Name = 'TestEvent';
		newEvent.Date__c = Date.today().addDays(1);
		insert newEvent;
		Event_Attendee__c newAttendee = new Event_Attendee__c();
		newAttendee.Attendee_Contact__c = contact.Id;
		newAttendee.Trade_Ally_Event__c = newEvent.Id;
		insert newAttendee;
	}

	@IsTest
	static void getInitDataTest() {
		List<Object> initDataList = TradeAllyEventsController.getInitData();
		List<Trade_Ally_Event__c> eventsList = (List<Trade_Ally_Event__c>) initDataList[0];
		System.assertEquals('TestEvent', eventsList[0].Name);
	}

	@IsTest
	static void getIsAdminProfileTest() {
		Profile currentProfile;
		Boolean userIsAdmin = false;
		currentProfile = [
				SELECT Name,
						PermissionsModifyAllData
				FROM Profile
				WHERE Id = :UserInfo.getProfileId()
		];
		if (currentProfile != null && currentProfile.PermissionsModifyAllData) {
			userIsAdmin = true;
		}
		System.assertEquals(userIsAdmin, TradeAllyEventsController.getIsAdminProfile());
	}
    
    @IsTest
	static void updateAttendeeTest() {
        Trade_Ally_Event__c tradeAllyEvent = [
				SELECT Name, Id,
            	(
						SELECT Id
						FROM Event_Attendees__r
				)
				FROM Trade_Ally_Event__c
				LIMIT 1
		];
        Event_Attendee__c currentAttendee = [
				SELECT Attendee_Contact__c,
						Trade_Ally_Event__c
				FROM Event_Attendee__c
				LIMIT 1
		];
        System.assertEquals(1, tradeAllyEvent.Event_Attendees__r.size());
        List<Id> newAttendees = new List<Id>();
        List<Id> deleteAttendees = new List<Id>();
        newAttendees.add(currentAttendee.Attendee_Contact__c);
        deleteAttendees.add(currentAttendee.Attendee_Contact__c);
        TradeAllyEventsController.updateAttendees(tradeAllyEvent.Id, newAttendees, deleteAttendees);
        tradeAllyEvent = [
				SELECT Name, (
						SELECT Id
						FROM Event_Attendees__r
				)
				FROM Trade_Ally_Event__c
				LIMIT 1
		];
		System.assertEquals(0, tradeAllyEvent.Event_Attendees__r.size());
    }
}