src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>External Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Name_Text__c</fullName>
        <description>This field holds the Project name that comes from DSMC in a nightly batch and is a string value.</description>
        <label>Project Name Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partners__c</fullName>
        <label>Partners</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProgramLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProgramLookup</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA Latest Data/main/default/objects/Trade_Ally_Project__c/Trade_Ally_Project__c.object-meta.xml
<CustomObject>
    <label>Trade Ally Project</label>
    <nameField>
        <displayFormat>TAPN-{0000}</displayFormat>
        <label>Trade Ally Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA Latest Data/main/default/objects/Trade_Ally_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Trade Ally Projects</relationshipLabel>
    <relationshipName>Trade_Ally_Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QA Latest Data/main/default/objects/Trade_Ally_Project__c/fields/Trade_Ally__c.field-meta.xml
<CustomField>
    <fullName>Trade_Ally__c</fullName>
    <label>Trade Ally</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trade Ally Projects</relationshipLabel>
    <relationshipName>Trade_Ally_Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectShareWithTATest.cls
@isTest
private class ProjectShareWithTATest {
    @testSetup static void setup() {
        // Create an account
        Account acct = new Account(Name='Test Account');
        acct.external_Id__c = '1';
        insert acct;
        // Create a contact
        Contact contact = new Contact();
        contact.Lastname ='test';
        contact.Level__c = 'Primary';
        contact.AccountId = acct.id;
        insert contact;
        //Create a user
        Profile profile = [SELECT Id FROM Profile WHERE Name='Custom Customer Community Plus']; 
        User user = new User(Alias = 'aliasTst', Email='opatzke@nexant.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser@testorg.com');
        user.ContactId = contact.Id;
        insert user;
    }
    
    // Test for the manual Share
    @isTest static void testManualShareInsert(){
        User user = [SELECT Id FROM User WHERE UserName='testuser@testorg.com' LIMIT 1];
        // Create new program
        Program__c p = new Program__c();
        p.Name = 'Test Program';
        insert p;
        // Create new project
        Project__c project = new Project__c();
        project.Name_Text__c = 'Test Project';
        project.ProgramLookup__c = p.Id;
        project.Partners__c = '1;';
        Test.startTest();
        insert project;
        Test.stopTest();
        
        // Query job sharing records.
        List<Project__Share> jShrs = [SELECT Id, UserOrGroupId, AccessLevel, 
                                       RowCause FROM Project__share WHERE ParentId = :project.Id AND UserOrGroupId= :user.Id];
        // Query junction records.
        List<Trade_Ally_Project__c> junctions = [SELECT Id, Trade_Ally__c FROM Trade_Ally_Project__c WHERE Project__c = :project.Id];
        
        // Test for only one manual share on job.
        System.assertEquals(jShrs.size(), 1, 'Set the object\'s sharing model to Private.');
        // Test attributes of manual share.
        System.assertEquals(jShrs[0].AccessLevel, 'Read');
        System.assertEquals(jShrs[0].RowCause, 'Manual');
        System.assertEquals(jShrs[0].UserOrGroupId, user.Id);
        
        System.assertEquals(junctions.size(), 1);
        System.assert((junctions[0].Trade_Ally__c) != null);
    }
    
    // Test for the manual Share
    @isTest static void testManualShareUpdate(){
        User user = [SELECT Id FROM User WHERE UserName='testuser@testorg.com' LIMIT 1];
        // Create new program
        Program__c p = new Program__c();
        p.Name = 'Test Program';
        insert p;
        // Create new project
        Project__c project = new Project__c();
        project.Name_Text__c = 'Test Project';
        project.ProgramLookup__c = p.Id;
        insert project;
        
        project.Partners__c = '1;';
        Test.startTest();
        update project;
        Test.stopTest();
        
        // Query job sharing records.
        List<Project__Share> jShrs = [SELECT Id, UserOrGroupId, AccessLevel, 
                                       RowCause FROM Project__share WHERE ParentId = :project.Id AND UserOrGroupId= :user.Id];
        
        // Query junction records.
        List<Trade_Ally_Project__c> junctions = [SELECT Id, Trade_Ally__c FROM Trade_Ally_Project__c WHERE Project__c = :project.Id];
         
        // Test for only one manual share on job.
        System.assertEquals(jShrs.size(), 1, 'Set the object\'s sharing model to Private.');
        // Test attributes of manual share.
        System.assertEquals(jShrs[0].AccessLevel, 'Read');
        System.assertEquals(jShrs[0].RowCause, 'Manual');
        System.assertEquals(jShrs[0].UserOrGroupId, user.Id);
        
        System.assertEquals(junctions.size(), 1);
        System.assert((junctions[0].Trade_Ally__c) != null);
    }
    
    // Test for the manual Share
    @isTest static void testManualShareUpdateToNull(){
        User user = [SELECT Id FROM User WHERE UserName='testuser@testorg.com' LIMIT 1];
        // Create new program
        Program__c p = new Program__c();
        p.Name = 'Test Program';
        insert p;
        // Create new project
        Project__c project = new Project__c();
        project.Name_Text__c = 'Test Project';
        project.ProgramLookup__c = p.Id;
        project.Partners__c = '1;';
        insert project;
        
        project.Partners__c = null;
        Test.startTest();
        update project;
        Test.stopTest();
        
        // Query job sharing records.
        List<Project__Share> jShrs = [SELECT Id, UserOrGroupId, AccessLevel, 
                                       RowCause FROM Project__share WHERE ParentId = :project.Id AND UserOrGroupId= :user.Id];
        // Query junction records.
        List<Trade_Ally_Project__c> junctions = [SELECT Id, Trade_Ally__c FROM Trade_Ally_Project__c WHERE Project__c = :project.Id];
        
        // Test for no manual share on project.
        System.assertEquals(jShrs.size(), 0, 'Set the object\'s sharing model to Private.');
        System.assertEquals(junctions.size(), 0);
    }
    
    // Test for the manual Share
    @isTest static void testManualShareException(){
         // Create an account
        Account acct = new Account(Name='Test Exception Account');
        acct.external_Id__c = '10';
        insert acct;
        // Create a contact
        Contact contact = new Contact();
        contact.Lastname ='Exceptiontest';
        contact.Level__c = 'Primary';
        contact.AccountId = acct.id;
        insert contact;
        //Create a user
        Profile profile = [SELECT Id FROM Profile WHERE Name='Custom Community Profile'];
        User user = new User(Alias = 'aliasStd', Email='opatzke@nexant.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = profile.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='teststduser@testorg.com');
        user.ContactId = contact.Id;
        insert user;
        // Create new program
        Program__c p = new Program__c();
        p.Name = 'Test Program';
        insert p;
        // Create new project
        Project__c project = new Project__c();
        project.Name_Text__c = 'Test Project';
        project.ProgramLookup__c = p.Id;
        project.Partners__c = '10;';
        try {
            Test.startTest();
            insert project;
            Test.stopTest();
        } catch (Exception error) {
            System.assertEquals(error.getMessage().contains('Unable to grant sharing access'), true);
        }
    }
}