src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Structure__c</fullName>
        <label>Business Structure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>General Partnership</fullName>
                </value>
                <value>
                    <fullName>C Corporation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Incorporation</fullName>
                </value>
                <value>
                    <fullName>LLC</fullName>
                </value>
                <value>
                    <fullName>S Corporation</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Types</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>Contractor</fullName>
                </value>
                <value>
                    <fullName>Design-Build Firm</fullName>
                </value>
                <value>
                    <fullName>Distribution / Wholesaler</fullName>
                </value>
                <value>
                    <fullName>Energy Managment / DR</fullName>
                </value>
                <value>
                    <fullName>Engineering Services</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Retailer</fullName>
                </value>
                <value>
                    <fullName>Supplier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legal_Company_Name__c</fullName>
        <label>Legal Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>President_Owner_of_Company__c</fullName>
        <label>Principal/President/Owner of Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Projects_Completed__c</fullName>
        <label>Projects Completed</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/testSecurityUtils.cls
/*----------------------------------------------------------------------------------------------- */
/*                                                                                                */
/* This class contains test methods for SFDCSecurityUtils class.                                  */
/*                                                                                                */
/* METHODS AND CLASSES:                                                                           */
/* test_insert:                 runs tests for SFDCSecurityUtils.                                 */
/* test_update:                 runs tests for SFDCSecurityUtils.                                 */
/* test_upsert:                 runs tests for SFDCSecurityUtils.                                 */
/* test_delete:                 runs tests for SFDCSecurityUtils.                                 */
/* test_updateEx:               runs tests for SFDCSecurityUtils.                                 */
/* test_insertEx:               runs tests for SFDCSecurityUtils.                                 */
/* test_insertEx2:              runs tests for SFDCSecurityUtils.                                 */
/*                                                                                                */
/*------------------------------------------------------------------------------------------------*/

@isTest(SeeAllData = false)
private class testSecurityUtils {

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_insert                                                                        */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_insert(){
        Test.startTest();
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
		testAcc.Projects_Completed__c = 0;
		testAcc.Business_Type__c = 'Contractor';
		testAcc.Status__c = 'Active';
		testAcc.Legal_Company_Name__c = 'test';
		testAcc.Business_Structure__c = 'Other';
		testAcc.President_Owner_of_Company__c = 'test';
        ESAPI.securityUtils().validatedInsert(new List<Account>{testAcc});
        System.assert(![SELECT Id FROM Account WHERE Name = 'Test Name'].isEmpty());
        Test.stopTest();
    }

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_update                                                                        */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_update(){
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
		testAcc.Projects_Completed__c = 0;
		testAcc.Business_Type__c = 'Contractor';
		testAcc.Status__c = 'Active';
		testAcc.Legal_Company_Name__c = 'test';
		testAcc.Business_Structure__c = 'Other';
		testAcc.President_Owner_of_Company__c = 'test';
        insert testAcc;
        testAcc.Name = 'Test Name2';
        Test.startTest();
        ESAPI.securityUtils().validatedUpdate(new List<Account>{testAcc});
        ESAPI.securityUtils().validatedUpsert(new List<Account>{testAcc});
        System.assert([SELECT Name FROM Account WHERE Id = :testAcc.Id][0].Name == 'Test Name2');
        Test.stopTest();
    }

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_upsert                                                                        */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_upsert(){
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
		testAcc.Projects_Completed__c = 0;
		testAcc.Business_Type__c = 'Contractor';
		testAcc.Status__c = 'Active';
		testAcc.Legal_Company_Name__c = 'test';
		testAcc.Business_Structure__c = 'Other';
		testAcc.President_Owner_of_Company__c = 'test';
        insert testAcc;
        testAcc.Name = 'Test Name2';
        Test.startTest();
        ESAPI.securityUtils().validatedUpsert(
			new List<Account>{
                testAcc, 
                new Account(
					Name = 'Test2',
					Projects_Completed__c = 0,
					Business_Type__c = 'Contractor',
					Status__c = 'Active',
					Legal_Company_Name__c = 'test',
					Business_Structure__c = 'Other', 
					President_Owner_of_Company__c = 'test'
				)
            }
        );
        System.assert(![SELECT Id FROM Account WHERE Name = 'Test Name2'].isEmpty());
        Test.stopTest();
    }

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_delete                                                                        */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_delete(){
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
		testAcc.Projects_Completed__c = 0;
		testAcc.Business_Type__c = 'Contractor';
		testAcc.Status__c = 'Active';
		testAcc.Legal_Company_Name__c = 'test';
		testAcc.Business_Structure__c = 'Other';
		testAcc.President_Owner_of_Company__c = 'test';
        insert testAcc;
        Test.startTest();
        ESAPI.securityUtils().validatedDelete(new List<Account>{testAcc});
        System.assert([SELECT Id FROM Account WHERE Name = 'Test Name'].isEmpty());
        Test.stopTest();
    }

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_updateEx                                                                      */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_updateEx(){
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
		testAcc.Projects_Completed__c = 0;
		testAcc.Business_Type__c = 'Contractor';
		testAcc.Status__c = 'Active';
		testAcc.Legal_Company_Name__c = 'test';
		testAcc.Business_Structure__c = 'Other';
		testAcc.President_Owner_of_Company__c = 'test';
        insert testAcc;
        testAcc.Phone = 'test';
        Test.startTest();
        try{
            SFDCSecurityUtils.crudValue = true;
            ESAPI.securityUtils().validatedUpdate(new List<Account>{testAcc});
        }catch(SFDCSecurityUtils.SFDC_FLS_Exception e){
            System.assert(e != null);
        }
        Test.stopTest();
    }

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_insertEx                                                                      */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_insertEx(){
        Account testAcc = new Account();
        testAcc.Name = 'Test Name';
		testAcc.Projects_Completed__c = 0;
		testAcc.Business_Type__c = 'Contractor';
		testAcc.Status__c = 'Active';
		testAcc.Legal_Company_Name__c = 'test';
		testAcc.Business_Structure__c = 'Other';
		testAcc.President_Owner_of_Company__c = 'test';
        testAcc.Phone = 'test';
        Test.startTest();
        try{
            SFDCSecurityUtils.crudValue = true;
            ESAPI.securityUtils().validatedInsert(new List<Account>{testAcc});
        }catch(SFDCSecurityUtils.SFDC_FLS_Exception e){
            System.assert(e != null);
        }
        Test.stopTest();
    }

    /*--------------------------------------------------------------------------------------------*/
    /*                                                                                            */
    /* METHOD: test_insertEx2                                                                     */
    /*                                                                                            */
    /* This method runs tests for SFDCSecurityUtils.                                              */
    /*                                                                                            */
    /*--------------------------------------------------------------------------------------------*/

    static testmethod void test_insertEx2(){
        Contact testCont = new Contact();
        testCont.FirstName = 'test';
        testCont.LastName = 'test';
		testCont.Level__c = 'Primary';
        Test.startTest();
        try{
            SFDCSecurityUtils.crudValue = true;
            ESAPI.securityUtils().validatedInsert(new List<Contact>{testCont});
        }catch(SFDCSecurityUtils.SFDC_CRUD_Exception e){
            System.assert(e != null);
        }
        Test.stopTest();
    }
}