src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trade Ally Subscriptions</relationshipLabel>
        <relationshipName>Trade_Ally_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Level</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Trade Ally Subscriptions</relationshipLabel>
        <relationshipName>Trade_Ally_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trade Ally Subscription</label>
    <nameField>
        <displayFormat>TASub-{000000}</displayFormat>
        <label>TA Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/classes/SubscriptionPopUpController.cls
global with sharing class SubscriptionPopUpController{
	@AuraEnabled
	public static String activateStandardSubscription(String applicationId) {
		String serverStatus = 'Your subscription level is Basic';
		Account account;
		if (
			ESAPI.securityUtils().isAuthorizedToView('Account', new List<String>{'Id'}) &&
			ESAPI.securityUtils().isAuthorizedToView(
				'Trade_Ally_Subscription__c',
				new List<String>{'Id', 'Subscription_Status__c', 'Subscription_Level__c'}
			)	
		) {
			account = [
					SELECT
							Id, 
							(
								SELECT
										Id,
										Subscription_Status__c,
										Subscription_Level__r.Name
								FROM	Trade_Ally_Subscriptions__r
							)
					FROM	Account
					WHERE	Id IN (
									SELECT	Trade_Ally__c
									FROM	Application__c
									WHERE	Id = :applicationId
							)
					LIMIT 1
			];
		}
		Trade_Ally_Subscription__c currentSubscription;
		if (account.Trade_Ally_Subscriptions__r.size() > 0) {
			currentSubscription = account.Trade_Ally_Subscriptions__r[0];
			currentSubscription.Subscription_Status__c = 'Active';
			serverStatus = 'Subscription is activated';
		}
		else {
			currentSubscription = new Trade_Ally_Subscription__c();
			currentSubscription.Account__c = account.Id;
			currentSubscription.Subscription_Status__c = 'Active';
			serverStatus = 'New active Subscription record is created';
		}
		try {
			ESAPI.securityUtils().validatedUpsert(new List<Trade_Ally_Subscription__c>{currentSubscription});
		}
		catch (Exception e) {
			serverStatus = 'The following exception has occurred: ' + e.getMessage();
		}
		return serverStatus;
	}
}