src/objects/Application__c.object
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Certification__c.object
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>General Liability</fullName>
                </value>
                <value>
                    <fullName>Workers Comp</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Other_Document__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Signed Agreement</fullName>
                    <default>true</default>
                    <label>Signed Agreement</label>
                </value>
                <value>
                    <fullName>Safety Protocol</fullName>
                </value>
                <value>
                    <fullName>Safety Records</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Other Document</label>
    <nameField>
        <label>Other Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Other Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tax__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>W-9</fullName>
                    <default>true</default>
                    <label>W-9</label>
                </value>
                <value>
                    <fullName>W-590</fullName>
                </value>
                <value>
                    <fullName>W-587</fullName>
                </value>
                <value>
                    <fullName>W-990</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tax</label>
    <nameField>
        <label>Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/classes/DocumentUploadControllerTest.cls
@IsTest 
private class DocumentUploadControllerTest {
	@IsTest
	private static void testServerGetLicenseFieldSet() {
		List<Object> fieldSets = DocumentUploadController.serverGetLicenseFieldSet();
		System.assert(fieldSets != null);
		System.assert(fieldSets.size() > 0);
	}

	@IsTest
	private static void testServerGetInsuranceFieldSet() {
		List<Object> fieldSets = DocumentUploadController.serverGetInsuranceFieldSet();
		System.assert(fieldSets != null);
		System.assert(fieldSets.size() > 0);
	}

	@IsTest
	private static void testServerGetCertificationFieldSet() {
		List<Object> fieldSets = DocumentUploadController.serverGetCertificationFieldSet();
		System.assert(fieldSets != null);
		System.assert(fieldSets.size() > 0);
	}

	@IsTest
	private static void testServerGetTaxFieldSet() {
		List<Object> fieldSets = DocumentUploadController.serverGetTaxFieldSet();
		System.assert(fieldSets != null);
		System.assert(fieldSets.size() > 0);
	}

	@IsTest
	private static void testServerGetOtherDocumentFieldSet() {
		List<Object> fieldSets = DocumentUploadController.serverGetOtherDocumentFieldSet();
		System.assert(fieldSets != null);
		System.assert(fieldSets.size() > 0);
	}

	@IsTest
	private static void testServerGetExistingRecords() {
		String applicationId;
		List<SObject> output;

		// has applicationId and objectType
		// TODO: there is no easy way of creating mock Application__c, User, and Account :( 

		// has applicationId, but invalid objectType
		output = DocumentUploadController.serverGetExistingRecords('', 'Random_Type__c');
		System.assert(output == null);

		// has objectType, but no applicationId
		output = DocumentUploadController.serverGetExistingRecords('', 'License__c');
		output = DocumentUploadController.serverGetExistingRecords('', 'Insurance__c');
		output = DocumentUploadController.serverGetExistingRecords('', 'Certification__c');
		output = DocumentUploadController.serverGetExistingRecords('', 'Tax__c');
		output = DocumentUploadController.serverGetExistingRecords('', 'Other_Document__c');

		// has no valid argument
		output = DocumentUploadController.serverGetExistingRecords('', '');
		System.assert(output == null);
	}

	@IsTest
	private static void testServerGetRelatedDocuments() {
		List<String> output;

		// invalid recordId results in null
		output = DocumentUploadController.serverGetRelatedDocuments(null);
		System.assert(output == null);

		output = DocumentUploadController.serverGetRelatedDocuments('');
		System.assert(output == null);

		// valid recordId
		License__c obj = new License__c(Type__c='ABC');
		insert obj;
		output = DocumentUploadController.serverGetRelatedDocuments(obj.Id);
		System.assert(output != null); 
	}
}