src/objects/Application_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trade Ally Subscriptions</relationshipLabel>
        <relationshipName>Trade_Ally_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stripe_Product_Name__c</fullName>
        <label>Stripe Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription Level</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Trade Ally Subscriptions</relationshipLabel>
        <relationshipName>Trade_Ally_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Status__c</fullName>
        <label>Subscription Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Trade Ally Subscription</label>
    <nameField>
        <displayFormat>TASub-{000000}</displayFormat>
        <label>TA Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/force-app/main/default/classes/SubscriptionTriggerTest.cls
@IsTest
private class SubscriptionTriggerTest {

	@TestSetup
	static void methodName() {
        Profile portalProfile = [
				SELECT
						Id,
						Name
				FROM    Profile
				WHERE   Name LIKE '%Custom Community Profile%'
				LIMIT   1
		];
		Id tradeAllyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Constants.TRADE_ALLY_RECORD_TYPE_NAME).getRecordTypeId();
		UserRole portalRole = [
				SELECT
						Id
				FROM    UserRole
				WHERE   PortalType = 'None'
				LIMIT   1
		];
		Profile profileSA = [
				SELECT
						Id
				FROM    Profile
				WHERE   Name = 'System Administrator'
		];
		List<User> portalAccountOwnerList = new List<User>();
		for (Integer i = 0; i < 10; i++) {
			User portalAccountOwner = new User(
					UserRoleId = portalRole.Id,
					ProfileId = profileSA.Id,
					Username = System.now().millisecond() + 'test2@test.com' + i,
					Alias = 'batman' + i,
					Email= i + 'bruce.wayne@wayneenterprises.com',
					EmailEncodingKey='UTF-8',
					FirstName='BruceBruce' + i,
					LastName='WayneWayne' + i,
					LanguageLocaleKey='en_US',
					LocaleSidKey='en_US',
					TimeZoneSidKey='America/Chicago'
			);
			portalAccountOwnerList.add(portalAccountOwner);
		}
		Database.insert(portalAccountOwnerList);
		List<Account> accountList = new List<Account>();
		for (Integer i = 0; i < 10; i++) {
			Account portalAccount = new Account(
					Name = 'TestAccount' + i,
					OwnerId = portalAccountOwnerList[i].Id,
					RecordTypeId = tradeAllyRecordTypeId
			);
			accountList.add(portalAccount);
		}
		System.runAs(portalAccountOwnerList[0]) {
			insert accountList;
            Application_Settings__c setting = new Application_Settings__c(
			Name = Constants.SUBSCRIBED_PROFILE_NAME,
			Value__c = 'Custom Customer Community Plus'
		);
		insert setting;
		}
		List<Contact> contactList = new List<Contact>();
		for (Account account : accountList) {
			Contact contact = new Contact(
					FirstName = 'Test ' + account.Name,
					LastName = 'McTesty '  + account.Name,
					AccountId = account.Id,
					Email = account.Name + System.now().millisecond() + 'test@test.com',
					Level__c = 'Tier 1'
			);
			contactList.add(contact);
		}
		System.runAs(portalAccountOwnerList[0]) {
			insert contactList;
		}

		List<User> userList = new List<User>();
		for (Integer i = 0; i < 10; i++) {
			User user = new User(
					Username = i + System.now().millisecond() + 'test12345@test.com',
					ContactId = contactList[i].Id,
					ProfileId = portalProfile.Id,
					Alias = 'test123' + i,
					Email = i +'test12345@test.com',
					EmailEncodingKey = 'UTF-8',
					LastName = 'McTestyMcTesty' + i,
					CommunityNickname = 'test12345' + i,
					TimeZoneSidKey = 'America/Los_Angeles',
					LocaleSidKey = 'en_US',
					LanguageLocaleKey = 'en_US'
			);
			userList.add(user);
		}
	System.runAs(portalAccountOwnerList[0]) {
		insert userList;
	}

		List<Product2> product2List = new List<Product2>();
		Product2 firstProduct = new Product2();
		firstProduct.Name = 'Trade Ally Plus Test';
		product2List.add(firstProduct);
		Product2 secondProduct = new Product2();
		secondProduct.Name = 'Trade Ally Basic Test';
		product2List.add(secondProduct);
		System.runAs(portalAccountOwnerList[0]) {
			insert product2List;
		}
		PermissionSet newPermissionSet = new PermissionSet(
				Name = firstProduct.Name.replaceAll(' ', '_'),
				Label = firstProduct.Name
		);
		System.runAs(portalAccountOwnerList[0]) {
			insert newPermissionSet;
		}
		List<Trade_Ally_Subscription__c> tradeAllySubscriptions = new List<Trade_Ally_Subscription__c>();
		for (Account account : accountList) {
			Trade_Ally_Subscription__c newSubscription = new Trade_Ally_Subscription__c(
					Account__c = account.Id,
					Subscription_Level__c = secondProduct.Id,
					Subscription_Status__c = 'Active',
					Stripe_Product_Name__c ='Trade Ally Plus Test'
			);
			tradeAllySubscriptions.add(newSubscription);
		}
		System.runAs(portalAccountOwnerList[0]) {
			insert tradeAllySubscriptions;
		}
	}

	@IsTest
	static void testBehavior() {
		List<Product2> product2s = [
				SELECT  Id,
						Name
				FROM    Product2
		];
		Product2 firstProduct;
		Product2 secondProduct;
		for (Product2 product2 : product2s) {
			if(product2.Name == 'Trade Ally Plus Test'){
				firstProduct = product2;
			}
			else{
				secondProduct = product2;
			}
		}
		System.debug('firstProduct ' + firstProduct);
		System.debug('secondProduct ' + secondProduct);
		List<Trade_Ally_Subscription__c> subscriptions = [
				SELECT Id,
						Subscription_Status__c,
						Subscription_Level__c
				FROM Trade_Ally_Subscription__c
				WHERE Subscription_Status__c = 'Active'
		];
		List<PermissionSet> permissionSets = [
				SELECT Id
				FROM PermissionSet
				WHERE Name = 'Trade_Ally_Plus_Test'
				OR Name = 'Trade_Ally_Basic_Test'
		];
		System.debug('permissionSets ' + permissionSets);
		System.debug('subscriptions ' + subscriptions);

		Map<Id, PermissionSet> permissionSetsMap = new Map<Id, PermissionSet>(permissionSets);
		System.debug('permissionSetsMap.keySet() ' + permissionSetsMap.keySet());

		List<PermissionSetAssignment> permissionSetAssignments = [
				SELECT
						Id
				FROM    PermissionSetAssignment
				WHERE Id IN: permissionSetsMap.keySet()
		];
		System.assertEquals(0, permissionSetAssignments.size());
		for (Trade_Ally_Subscription__c tradeAllySubscription : subscriptions) {
			tradeAllySubscription.Subscription_Level__c = firstProduct.Id;
			tradeAllySubscription.Subscription_Status__c = 'Active';
		}
		update subscriptions;
		permissionSetAssignments = [
				SELECT
						Id
				FROM    PermissionSetAssignment
				WHERE PermissionSetId IN: permissionSetsMap.keySet()

		];
		System.assertEquals(0, permissionSetAssignments.size());
		for (Trade_Ally_Subscription__c tradeAllySubscription : subscriptions) {
			tradeAllySubscription.Subscription_Level__c = secondProduct.Id;
		}
		update subscriptions;
		permissionSetAssignments = [
				SELECT
						Id
				FROM    PermissionSetAssignment
				WHERE PermissionSetId IN: permissionSetsMap.keySet()

		];
		System.assertEquals(0, permissionSetAssignments.size());
		for (Trade_Ally_Subscription__c tradeAllySubscription : subscriptions) {
			tradeAllySubscription.Subscription_Status__c = 'Inactive';
		}
		update subscriptions;
		permissionSetAssignments = [
				SELECT
						Id
				FROM    PermissionSetAssignment
				WHERE PermissionSetId IN: permissionSetsMap.keySet()

		];
		System.assertEquals(0, permissionSetAssignments.size());
		for (Trade_Ally_Subscription__c tradeAllySubscription : subscriptions) {
			tradeAllySubscription.Subscription_Status__c = 'Active';
		}
		update subscriptions;
		permissionSetAssignments = [
				SELECT
						Id
				FROM    PermissionSetAssignment
				WHERE PermissionSetId IN: permissionSetsMap.keySet()

		];
		System.assertEquals(0, permissionSetAssignments.size());
		delete subscriptions;
		permissionSetAssignments = [
				SELECT
						Id
				FROM    PermissionSetAssignment
				WHERE PermissionSetId IN: permissionSetsMap.keySet()

		];
		System.assertEquals(0, permissionSetAssignments.size());
	}


}