src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Approved_Application__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Approved Application</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ApplicationOnChangeTriggerHandler.cls
public with sharing class ApplicationOnChangeTriggerHandler {

	public static void reviewApplicationStatus(List<Application__c> listOfNewApps) {
		Map<Id,Boolean> mapOfInfoByAccountId = new Map<Id,Boolean>();
		for (Application__c newApp : listOfNewApps) {
			if (newApp.Trade_Ally__c != null) {
				mapOfInfoByAccountId.put(
					newApp.Trade_Ally__c,
					(newApp.Application_Status__c == 'Active')
				);
			}
		}
		System.debug('mapOfInfoByAccountId '+mapOfInfoByAccountId);
		List<User> listOfCommunityUsers = new List<User>();
		if (
			ESAPI.securityUtils().isAuthorizedToView(
				'User',
				new List<String>{
					'Id',
					'ContactId',
					Constants.NAMESPACE + 'Approved_Application__c'
				}
			) &&
			ESAPI.securityUtils().isAuthorizedToView(
				'Contact',
				new List<String>{
					'AccountId'
				}
			)
		) {
			listOfCommunityUsers = [
				SELECT
						Id,
						Contact.AccountId,
						Approved_Application__c
				FROM	User
				WHERE	Contact.AccountId IN: mapOfInfoByAccountId.keySet()
			];
		}
		List<User> listOfCommunityUsersToUpdate = new List<User>();
		for (User u : listOfCommunityUsers) {
			if (u.Approved_Application__c != mapOfInfoByAccountId.get(u.Contact.AccountId)) {
				u.Approved_Application__c = mapOfInfoByAccountId.get(u.Contact.AccountId);
				listOfCommunityUsersToUpdate.add(u);
			}
		}
		ESAPI.securityUtils().validatedUpdate(listOfCommunityUsersToUpdate);
	}
}