src/objects/Certification__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>General Liability</fullName>
                </value>
                <value>
                    <fullName>Workers Comp</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA Latest Data/main/default/classes/GenerateAlertTriggersTest.cls
@IsTest
private class GenerateAlertTriggersTest {

	private static final Integer NUMBER_OF_RECORDS = 20;

	@IsTest
	static void testGenerateAlertTriggers() {
		License__c license = new License__c(
			Type__c = 'test',
			Expiry_Date__c = Date.today()
		);
		insert license;
		update license;

		Insurance__c insurance = new Insurance__c(
			Expiry_Date__c = Date.today()
		);
		insert insurance;

		Certification__c certification = new Certification__c(
			Expiry_Date__c = Date.today()
		);
		insert certification;

		List<Task> listOfTasks = [
			SELECT	Id
			FROM	Task
		];
		System.assert(listOfTasks.size() == 3);
	}
	/*private static void createAlertTest(String sObjectType, String alertFieldApi, String expirationDateFieldApi) {
		//Test after insert action
		List<sObject> testLicenses = new List<sObject>();
		Date testExpirationDate = Date.valueOf('2018-10-05');// 20:00:00
		for (Integer i = 0; i < GenerateAlertTriggersTest.NUMBER_OF_RECORDS; i++) {
			sObject testLicense = Schema.getGlobalDescribe().get(sObjectType).newSObject();
			if (math.mod(i, 2) == 0) {
				testLicense.put(expirationDateFieldApi, testExpirationDate);
			}
			testLicenses.add(testLicense);
		}
		insert testLicenses;
		List<Task> alertsResult = [
			SELECT 	Id,
					ActivityDate
			FROM 	Task
			LIMIT 	50000
		];
		System.assert(!alertsResult.isEmpty());
		System.assert(alertsResult.size() == GenerateAlertTriggersTest.NUMBER_OF_RECORDS / 2);
		for (Task alert : alertsResult) {
			System.assert(alert.ActivityDate != null);
			System.assert(alert.ActivityDate.format() == '10/5/2018');// 8:00 PM
		}
		//Test after update action
		for (Integer i = 0; i < GenerateAlertTriggersTest.NUMBER_OF_RECORDS; i++) {
			if (math.mod(i, 2) != 0) {
				testLicenses[i].put(expirationDateFieldApi, testExpirationDate);
			}
		}
		update testLicenses;
		alertsResult = [
			SELECT 	Id,
					ActivityDate
			FROM 	Task
			LIMIT 	50000
		];
		System.assert(!alertsResult.isEmpty());
		System.assert(alertsResult.size() == GenerateAlertTriggersTest.NUMBER_OF_RECORDS);
		for (Task alert : alertsResult) {
			System.assert(alert.ActivityDate != null);
			System.assert(alert.ActivityDate.format() == '10/5/2018');// 8:00 PM
		}
		//Test that all related records exist
		String relatedRecordsQuery = 'SELECT' + ' ' + alertFieldApi + ',' + ' ' + expirationDateFieldApi + ' ' + 'FROM' + ' ' + sObjectType + ' ' + 'LIMIT 50000';
		List<sObject> relatedRecordsResult = Database.query(relatedRecordsQuery);
		System.assert(!relatedRecordsResult.isEmpty());
		System.assert(relatedRecordsResult.size() == GenerateAlertTriggersTest.NUMBER_OF_RECORDS);
		for (sObject relatedRecord : relatedRecordsResult) {
			System.assert(relatedRecord.get(alertFieldApi) != null);
		}
	}

	//Test method for 'GenerateAlertBasedOnLicenseTrigger'
	@IsTest
	static void generateAlertBasedOnLicenseTest() {
		GenerateAlertTriggersTest.createAlertTest('License__c', 'ActivityDate');
	}

	//Test method for 'GenerateAlertBasedOnInsuranceTrigger'
	@IsTest
	static void generateAlertBasedOnInsuranceTest() {
		GenerateAlertTriggersTest.createAlertTest('Insurance__c', 'ActivityDate');
	}*/

}