src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Secondary</fullName>
                </value>
                <value>
                    <fullName>Tertiary</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Utility Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Status__c</fullName>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Customer Contacted</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>RRN-{000000}</displayFormat>
        <label>Referral Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Specialty__c.object
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Referral__c.object
<CustomObject>
    <fields>
        <fullName>Referral_Status__c</fullName>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Customer Contacted</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <isActive>false</isActive>
                    <label>Created</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Trade Ally Referrals</relationshipLabel>
        <relationshipName>Trade_Ally_Referrals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trade Ally Referrals</relationshipLabel>
        <relationshipName>Trade_Ally_Referrals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Trade Ally Referral</label>
    <nameField>
        <label>Trade Ally Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Ally Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/force-app/main/default/classes/TradeAllySearchControllerTest.cls
@IsTest
public with sharing class TradeAllySearchControllerTest {

	@IsTest
	public static void getSelectedTradeAlliesTest() {
		RecordType rt = [
			SELECT	Id
			FROM	RecordType
			WHERE	Name = 'Trade Ally'
		];
		Account newAccount = new Account(
			Name = 'Account',
			RecordTypeId = rt.Id
		);
		insert newAccount;
		Contact newContact = new Contact(
			LastName = 'Last Name',
			Level__c = 'Tier 1'
		);
		insert newContact;
		Referral__c newReferral = new Referral__c(
			Customer__c = newContact.Id//,
			//Trade_Ally__c = newAccount.Id
		);
		insert newReferral;
		Trade_Ally_Referral__c newTradeAllyReferral = new Trade_Ally_Referral__c(
				Trade_Ally__c = newAccount.Id,
				Referral__c = newReferral.Id,
				Referral_Status__c = 'Assigned'
		);
		insert newTradeAllyReferral;
		List<TradeAllySearchController.TradeAllyWrapper> newWrappers = TradeAllySearchController.getSelectedTradeallies(newReferral.Id);
		System.assertEquals(true, newWrappers != null);
	}

	@IsTest
	public static void createTradeAllyReferralRelationTest() {
		RecordType rt = [
			SELECT	Id
			FROM	RecordType
			WHERE	Name = 'Trade Ally'
		];
		Account newAccount = new Account(
			Name = 'Account',
			RecordTypeId = rt.Id
		);
		insert newAccount;
		List<TradeAllySearchController.TradeAllyWrapper> wrappers = new List<TradeAllySearchController.TradeAllyWrapper>();
		TradeAllySearchController.TradeAllyWrapper newWrapper;
		List<User> users = [
			SELECT Id,
					Latitude,
					Longitude
			FROM User
			WHERE Id =: UserInfo.getUserId()
		];
		for (Integer i = 0; i < 5; i++) {
			newWrapper = new TradeAllySearchController.TradeAllyWrapper(
				true,
				newAccount,
				users[0]
			);
			wrappers.add(newWrapper);
		}
		String serialisedAccounts = JSON.serialize(wrappers);
		Contact newContact = new Contact(
			LastName = 'Last Name',
			Level__c = 'Tier 1'
		);
		insert newContact;

		Referral__c newReferral = new Referral__c(
			Customer__c = newContact.Id//,
			//Trade_Ally__c = newAccount.Id
		);
		insert newReferral;
		TradeAllySearchController.createTradeAllyReferralRelation(serialisedAccounts, newReferral.Id);
        List<TradeAllySearchController.TradeAllyWrapper> newWrappers = TradeAllySearchController.getSelectedTradeallies(newReferral.Id);
		System.assertEquals(true, newWrappers != null);
	}

	@IsTest
	public static void getTradeAllyIdListTest() {
		Specialty__c newSpecialty = new Specialty__c(
				Name = 'Specialty'
		);
		List<Id>  specialtyNameOptions = TradeAllySearchController.getTradeAllyIdList(newSpecialty.Id);
		System.assertEquals(true, specialtyNameOptions != null);
	}

	@IsTest
	public static void getSpecialtyNameOptionsTest() {
		Map<String, String> specialtyNameOptions = TradeAllySearchController.getSpecialtyNameOptions();
		System.assertEquals(true, specialtyNameOptions != null);
	}

	@IsTest
	public static void getSectorsOptionsTest() {
		Map<String, String> specialtyNameOptions = TradeAllySearchController.getSectorsOptions();
		System.assertEquals(true, specialtyNameOptions != null);
	}

@IsTest
	public static void searchForTradeAlliesTest() {
	Specialty__c newSpecialty = new Specialty__c(
			Name = 'Specialty'
	);
	insert newSpecialty;
	List<TradeAllySearchController.TradeAllyWrapper> specialtyNameOptions = TradeAllySearchController.searchForTradeAllies(newSpecialty.Id, '');
	System.assertEquals(true, specialtyNameOptions != null);
	}



}