src/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attendee Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Event_Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Attendee_Name__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <formula>Attendee_Name__r.MobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Phone Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Ally_Event__c</fullName>
        <label>Trade Ally Event</label>
        <referenceTo>Trade_Ally_Event__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EAN-  {000000}</displayFormat>
        <label>Event Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee_Contact__c.field-meta.xml
<CustomField>
    <fullName>Attendee_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Attendee Contacts</relationshipLabel>
    <relationshipName>Attendee_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Specialty__c.object
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Event__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attendees_Enrolled__c</fullName>
        <label>Attendees Enrolled</label>
        <summaryForeignKey>Event_Attendee__c.Trade_Ally_Event__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Series__c</fullName>
        <label>Event Series</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Topic__c</fullName>
        <label>Event Topic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Certification</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maximum_Attendees__c</fullName>
        <label>Maximum Attendees</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Presenter_Name__c</fullName>
        <label>Presenter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialty</label>
        <referenceTo>Specialty__c</referenceTo>
        <relationshipLabel>Trade Ally Events</relationshipLabel>
        <relationshipName>Trade_Ally_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Spots_Remaining__c</fullName>
        <formula>Maximum_Attendees__c -  Attendees_Enrolled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spots Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>State_Incorporated</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eastern</fullName>
                </value>
                <value>
                    <fullName>Central</fullName>
                </value>
                <value>
                    <fullName>Mountain</fullName>
                </value>
                <value>
                    <fullName>Pacific</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Trade Ally Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Ally Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/State_Incorporated.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>default 1</fullName>
    </customValue>
    <customValue>
        <fullName>default 2</fullName>
    </customValue>
    <masterLabel>State Incorporated</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradeAllyEventsController.cls
global with sharing class TradeAllyEventsController {
    @AuraEnabled
	public static List<Contact> getListOfAllCompanyContacts() {
		Id currentUserAccountId = StartApplicationController.getCurrentUserInfo().Contact.AccountId;
		List<Contact> listOfAllCompanyContacts = new List<Contact>();
		List<String> fieldsToCheck = new List<String>{'Id'};
		if (ESAPI.securityUtils().isAuthorizedToView('Contact',fieldsToCheck)) {
			listOfAllCompanyContacts = [
				SELECT	Id, Name
				FROM	Contact
				WHERE	Contact.AccountId =: currentUserAccountId
			];
		}
		return listOfAllCompanyContacts;
	}

	@AuraEnabled
	public static List<Object> getInitData() {
		List<Object> initData = new List<Object>();
		List<Trade_Ally_Event__c> eventsList = getEvents();
		initData.add(eventsList);
		Boolean isAdminProfile = getIsAdminProfile();
		initData.add(isAdminProfile);
		return initData;
	}

	@AuraEnabled
	public static List<Trade_Ally_Event__c> getEvents() {
		List<Trade_Ally_Event__c> eventsList = new List<Trade_Ally_Event__c>();
		List<String> fieldsToCheck = new List<String>{
			'Id',
			'Name',
			Constants.NAMESPACE + 'Event_Topic__c',
			Constants.NAMESPACE + 'Specialty__c',
			Constants.NAMESPACE + 'Event_Series__c',
			Constants.NAMESPACE + 'Presenter_Name__c',
			Constants.NAMESPACE + 'Address__c',
			Constants.NAMESPACE + 'City__c',
			Constants.NAMESPACE + 'State__c',
			Constants.NAMESPACE + 'Zip_Code__c',
			Constants.NAMESPACE + 'Subject__c',
			Constants.NAMESPACE + 'Date__c',
			Constants.NAMESPACE + 'Time__c',
			Constants.NAMESPACE + 'To__c',
			Constants.NAMESPACE + 'Event_Type__c',
			Constants.NAMESPACE + 'Maximum_Attendees__c',
			Constants.NAMESPACE + 'Attendees_Enrolled__c',
			Constants.NAMESPACE + 'Spots_Remaining__c'
		};
		if (
			ESAPI.securityUtils().isAuthorizedToView(Constants.NAMESPACE + 'Trade_Ally_Event__c',fieldsToCheck) &&
			ESAPI.securityUtils().isAuthorizedToView(
				Constants.NAMESPACE + 'Event_Attendee__c',
				new List<String>{
					Constants.NAMESPACE + 'Attendee_Contact__c',
					Constants.NAMESPACE + 'Email__c',
					Constants.NAMESPACE + 'Phone_Number__c',
					Constants.NAMESPACE + 'Attendee_Name__c'
				}
			) &&
			ESAPI.securityUtils().isAuthorizedToView(
				'Contact',
				new List<String>{
                    'Id',
                    'Name',
					'LastName',
					'FirstName',
					'Email',
					'Phone'
				}
			)
		) {
			eventsList = [
				SELECT 
						Name,
						Event_Topic__c,
						Specialty__r.Name,
						Event_Series__c,
						Presenter_Name__c,
						Address__c,
						City__c,
						State__c,
						Zip_Code__c,
						Subject__c,
						Date__c,
						Time__c,
						To__c,
						Event_Type__c,
						Maximum_Attendees__c,
						Attendees_Enrolled__c,
						Spots_Remaining__c,
                		(
							SELECT	
									Id,
                            		Attendee_Contact__r.Id,
                            		Attendee_Contact__r.Name,
									Attendee_Contact__r.LastName,
									Attendee_Contact__r.FirstName,
									Attendee_Contact__r.Email,
									Attendee_Contact__r.Phone,
									Email__c,
									Phone_Number__c,
									Attendee_Contact__c
							FROM	Event_Attendees__r
						)
				FROM	Trade_Ally_Event__c
				WHERE	Date__c >= TODAY
			];
		}
		return eventsList;
	}
    
    @AuraEnabled
	public static void updateAttendees(String eventId, List<Id> newAttendees, List<Id> deleteAttendees) {
        System.debug('newAttendees '+newAttendees);
        System.debug('deleteAttendees '+deleteAttendees);
        eventId = String.isBlank(eventId) ? null : String.escapeSingleQuotes(eventId);
        //Create new Event_Attendee__c junctions objects
        if(newAttendees != null && newAttendees.size() > 0) {
            List<Event_Attendee__c> newInserts = new List<Event_Attendee__c>();
            for(Id contactId : newAttendees) {
                Event_Attendee__c newEventAttendee = new Event_Attendee__c();
                newEventAttendee.Attendee_Contact__c = contactId;
                newEventAttendee.Trade_Ally_Event__c = eventId;
                newInserts.add(newEventAttendee);
            }
            ESAPI.securityUtils().validatedInsert(newInserts);
        }
        //Remove existing Event_Attendee__c junctions objects
        if(deleteAttendees != null && deleteAttendees.size() > 0) {
            List<Event_Attendee__c> deleteList = new List<Event_Attendee__c>();
            if (ESAPI.securityUtils().isAuthorizedToView(Constants.NAMESPACE + 'Event_Attendee__c',new List<String>{'Id'})) {
                deleteList = [
                    SELECT	Id
                    FROM	Event_Attendee__c
                    WHERE 
                            Attendee_Contact__c IN: deleteAttendees AND
                            Trade_Ally_Event__c =: eventId
                ];
            }
            System.debug('deleteList ' + deleteList);
            ESAPI.securityUtils().validatedDelete(deleteList);
        }
    }
    
    @AuraEnabled
    public static ComponentDetail getComponentInfo(String eventId) {
        ComponentDetail compDetail = new ComponentDetail();
        compDetail.stateValues = getStateValues();
        compDetail.companyContacts = getListOfAllCompanyContacts();
        
        List<Trade_Ally_Event__c> tradeAllys = [SELECT Id, Date__c, Time__c, To__c, Time_Zone__c FROM Trade_Ally_Event__c WHERE Id = :eventId];
        if(tradeAllys[0].Time__c != null) {
            Datetime myDateTime = Datetime.newInstance(System.today(), tradeAllys[0].Time__c);
            compDetail.timeObj = myDateTime.format('h:mm a');
        }
        if(tradeAllys[0].To__c != null) {
            Datetime myDateTime = Datetime.newInstance(System.today(), tradeAllys[0].To__c);
            compDetail.toTimeObj = myDateTime.format('h:mm a');
        }
        
        return compDetail;
    }
    
    static Map<String, String> getStateValues (){
        Map<String, String> pickListValuesMap= new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Trade_Ally_Event__c.State__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesMap.put(pickListVal.getValue().toLowerCase(), pickListVal.getLabel());
        }     
        return pickListValuesMap;
    }
	@AuraEnabled
	public static Boolean getIsAdminProfile() {
		Profile profileRecord;
		if (ESAPI.securityUtils().isAuthorizedToView('Profile',new List<String>{'Name','PermissionsModifyAllData'})) {
			profileRecord = [
				SELECT 
						Name,
						PermissionsModifyAllData
				FROM	Profile
				WHERE	Id = :UserInfo.getProfileId()
			];
		}
		if (profileRecord != null && profileRecord.PermissionsModifyAllData) {
			return true;
		}
		return false;
	}
    
    public class ComponentDetail{
        @auraEnabled
        public  Map<String, String> stateValues;
        @auraEnabled
        public String toTimeObj {get; set;}
        @auraEnabled
        public List<Contact> companyContacts {get; set;}
        @auraEnabled
        public String timeObj {get; set;}
        
        public ComponentDetail(){
            stateValues = new Map<String, String>();
        }
    }

}