src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Trade_Ally_Subscription__c</fullName>
        <label>Trade Ally Subscription</label>
        <referenceTo>Trade_Ally_Subscription__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Stripe_Id__c</fullName>
        <label>Stripe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trade Ally Subscription</label>
    <nameField>
        <displayFormat>TASub-{000000}</displayFormat>
        <label>TA Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QA Latest Data/main/default/classes/GetStripeInvoicesSchedulerAndBatchTest.cls
@IsTest
public with sharing class GetStripeInvoicesSchedulerAndBatchTest {

	@TestSetup
	public static void testSetup() {
			Trade_Ally_Subscription__c newAllySubscription = new Trade_Ally_Subscription__c(
					Stripe_Id__c = 'subscription'
			);
			insert newAllySubscription;

	}

	@IsTest
	public static void schedulerTest() {
		Test.setMock(HttpCalloutMock.class, new StripeHttpCalloutMock());
		Test.startTest();
		String checkActiveRecordsSchedulerId1 = GetStripeInvoicesScheduler.runMe();
		new GetStripeInvoicesScheduler().execute(null);
		Test.stopTest();
		List<Invoice__c> invoices = [
				SELECT Id
				FROM Invoice__c
		];
		System.assertEquals(1, invoices.size());
	}


}