src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Trade_Ally_Subscription__c</fullName>
        <label>Trade Ally Subscription</label>
        <referenceTo>Trade_Ally_Subscription__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trade_Ally_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stripe_Id__c</fullName>
        <label>Stripe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trade Ally Subscription</label>
    <nameField>
        <displayFormat>TASub-{000000}</displayFormat>
        <label>TA Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Stripe_Id__c</fullName>
        <label>Stripe Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/GetStripeInvoicesBatch.cls
global class GetStripeInvoicesBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
	global static final Integer FREQUENCY_IN_DAYS = 1;
	global Database.QueryLocator start(Database.BatchableContext context) {
		String query = 'SELECT Id, ' +
				Constants.NAMESPACE + 'Customer__r.' +
				Constants.NAMESPACE + 'Stripe_Id__c, ' +
				Constants.NAMESPACE + 'Customer__c, ' +
				Constants.NAMESPACE + 'Stripe_Id__c FROM ' +
				Constants.NAMESPACE + 'Trade_Ally_Subscription__c ' +
				'WHERE ' + Constants.NAMESPACE + 'Stripe_Id__c != NULL';
		Database.QueryLocator ql;
		if (
				ESAPI.securityUtils().isAuthorizedToView(
						Constants.NAMESPACE + 'Trade_Ally_Subscription__c',
						new List<String>{
								'Id',
								Constants.NAMESPACE + 'Customer__c',
								Constants.NAMESPACE + 'Stripe_Id__c'
						}
				)&&
						ESAPI.securityUtils().isAuthorizedToView(
								'User',
								new List<String>{
										Constants.NAMESPACE + 'Stripe_Id__c'
								}
						)
				) {
			ql = Database.getQueryLocator(query);
		}
		return ql;
	}

	global void execute(Database.BatchableContext context, List<Trade_Ally_Subscription__c> scope) {
		Date today = Date.today();
		Date startDate = today.addDays(-FREQUENCY_IN_DAYS);
		Integer startDateUnix = StripeApiUtility.convertDateToUnix(startDate);
		List<Invoice__c> invoiceList = new List<Invoice__c>();
		for (Trade_Ally_Subscription__c tradeAllySubscription : scope) {
			String starting_after;
			List<Object> stripeInvoiceList = StripeApiUtility.getInvoices(tradeAllySubscription.Customer__r.Stripe_Id__c, tradeAllySubscription.Stripe_Id__c, starting_after, String.valueOf(startDateUnix));
			if(stripeInvoiceList == null) continue;
			while (Math.mod(stripeInvoiceList.size(), 10) == 0) {
				starting_after = (String) ((Map<String, Object>) stripeInvoiceList[stripeInvoiceList.size() - 1]).get('id');
				List<Object> additionalStripeInvoiceList = StripeApiUtility.getInvoices(tradeAllySubscription.Customer__r.Stripe_Id__c, tradeAllySubscription.Stripe_Id__c, String.valueOf(starting_after), String.valueOf(startDateUnix));
				if (additionalStripeInvoiceList.size() == 0) break;
				stripeInvoiceList.addAll(additionalStripeInvoiceList);
			}
			for (Object stripeInvoice : stripeInvoiceList) {
				Map<String, Object> invoiceMap = (Map<String, Object>) stripeInvoice;
				if ((String) invoiceMap.get('subscription') == tradeAllySubscription.Stripe_Id__c) {
					Invoice__c newInvoice = new Invoice__c(
							Trade_Ally_Subscription__c = tradeAllySubscription.Id,
							Customer__c = tradeAllySubscription.Customer__c,
							Invoice_Date__c = StripeApiUtility.convertDateFromUnix(Integer.valueOf(invoiceMap.get('date'))),
							Amount_Paid__c = (Decimal.valueOf((Integer)invoiceMap.get('amount_paid'))) / 100
					);
					invoiceList.add(newInvoice);
				}
			}

		}
		if (invoiceList.size() > 0) {
			ESAPI.securityUtils().validatedUpsert(invoiceList);
		}
	}

	global void finish(Database.BatchableContext context) {
	}
}