src/objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trade_Ally_License__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>License__c</referenceTo>
        <relationshipLabel>Trade Ally Licenses</relationshipLabel>
        <relationshipName>Trade_Ally_Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trade Ally License</label>
    <nameField>
        <displayFormat>TALN-{000000}</displayFormat>
        <label>Trade Ally License Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ValidateActiveLicensesBatch.cls
global class ValidateActiveLicensesBatch implements Database.Batchable<SObject> {
	
	global Database.QueryLocator start(Database.BatchableContext context) {
		Date today = Date.today();
		String query = 'SELECT Id, ' + Constants.NAMESPACE + 'License__r.' + 
						Constants.NAMESPACE + 'Expiry_Date__c, ' +
						Constants.NAMESPACE + 'Is_Active__c FROM ' +
						Constants.NAMESPACE + 'Trade_Ally_License__c ' +
						'WHERE ' + Constants.NAMESPACE + 'Is_Active__c = true AND ' +
						Constants.NAMESPACE + 'License__r.' + 
						Constants.NAMESPACE + 'Expiry_Date__c >= today';
		Database.QueryLocator ql;
		if (
			ESAPI.securityUtils().isAuthorizedToView(
				Constants.NAMESPACE + 'Trade_Ally_License__c',
				new List<String>{
					'Id',
					Constants.NAMESPACE + 'License__c',
					Constants.NAMESPACE + 'Is_Active__c'
				}
			) &&
			ESAPI.securityUtils().isAuthorizedToView(
				Constants.NAMESPACE + 'License__c',
				new List<String>{
					Constants.NAMESPACE + 'Expiry_Date__c'
				}
			)
		) {
			ql = Database.getQueryLocator(query);
		}
		return ql;
	}

   	global void execute(Database.BatchableContext context, List<Trade_Ally_License__c> scope) {
		for (Trade_Ally_License__c tradeAllyLicense : scope) {
			tradeAllyLicense.Is_Active__c = false;
		}
		ESAPI.securityUtils().validatedUpdate(scope);
	}
	
	global void finish(Database.BatchableContext context) {
		
	}
}