src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TA_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects (Trade Ally)</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trade_Ally_Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trade Ally Referral</label>
        <referenceTo>Trade_Ally_Referral__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Customer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Utility Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Status__c</fullName>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Customer Contacted</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>RRN-{000000}</displayFormat>
        <label>Referral Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Referral__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Trade Ally Referrals</relationshipLabel>
        <relationshipName>Trade_Ally_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral_Status__c</fullName>
        <label>Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Customer Contacted</fullName>
                </value>
                <value>
                    <fullName>Converted</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                    <isActive>false</isActive>
                    <label>Created</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Trade Ally Referrals</relationshipLabel>
        <relationshipName>Trade_Ally_Referrals</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Trade_Ally__c</fullName>
        <label>Trade Ally</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Trade Ally Referrals</relationshipLabel>
        <relationshipName>Trade_Ally_Referrals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Trade Ally Referral</label>
    <nameField>
        <label>Trade Ally Referral Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trade Ally Referrals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QA Latest Data/main/default/classes/ConvertReferralController.cls
public with sharing class ConvertReferralController {
    
    @AuraEnabled
    public static Boolean getRecordStatus(String recordId) {
        Trade_Ally_Referral__c taReferral;
        recordId = String.isBlank(recordId) ? null : String.escapeSingleQuotes(recordId);
        if (
            ESAPI.securityUtils().isAuthorizedToView(
                Constants.NAMESPACE + 'Trade_Ally_Referral__c',
                new List<String>{
                    'Id',
                    Constants.NAMESPACE + 'Program__c',
                    Constants.NAMESPACE + 'Referral_Status__c'
                }
            )/* &&
            ESAPI.securityUtils().isAuthorizedToView(
                Constants.NAMESPACE + 'Referral__c',
                new List<String>{
                    'Id',
                    Constants.NAMESPACE + 'Referral_Status__c'
                }
            )*/
        ) {
            taReferral = [
                SELECT  
                        Program__c,
                        Referral_Status__c
                FROM    Trade_Ally_Referral__c
                WHERE   Id =: recordId
            ];
        }
        return (
            (
                taReferral.Referral_Status__c != null &&
                (
                    taReferral.Referral_Status__c == 'Expired' ||
                    taReferral.Referral_Status__c == 'Converted'
                )
            ) ||
            taReferral.Program__c == null
        );
    }

    @AuraEnabled
    public static void startReferralConvertation(String recordId) {
        recordId = String.isBlank(recordId) ? null : String.escapeSingleQuotes(recordId);
        List<Trade_Ally_Referral__c> listOfTAReferrals = new List<Trade_Ally_Referral__c>();
        if (
            ESAPI.securityUtils().isAuthorizedToView(
                Constants.NAMESPACE + 'Trade_Ally_Referral__c',
                new List<String>{
                    'Id',
                    Constants.NAMESPACE + 'Referral__c',
                    Constants.NAMESPACE + 'Trade_Ally__c',
                    Constants.NAMESPACE + 'Program__c',
                    Constants.NAMESPACE + 'Referral_Status__c'
                }
            ) &&
            ESAPI.securityUtils().isAuthorizedToView(
                Constants.NAMESPACE + 'Referral__c',
                new List<String>{
                    'Id',
                    Constants.NAMESPACE + 'Customer__c'
                }
            )
        ) {
            listOfTAReferrals = [
                SELECT  
                        Id,
                        Trade_Ally__c,
                        Program__c,
                        Referral_Status__c,
                        Referral__c,
                        Referral__r.Customer__r.AccountId
                FROM    Trade_Ally_Referral__c
                WHERE   Id =: recordId
            ];
        }
        if (!listOfTAReferrals.isEmpty()) {
            List<Project__c> listOfNewProjects = new List<Project__c>();
            Project__c newProject = new Project__c(
                Referral__c = listOfTAReferrals[0].Referral__c,
                Trade_Ally_Referral__c = recordId,
                //Program__c = listOfTAReferrals[0].Program__c,
                TA_Account__c = listOfTAReferrals[0].Trade_Ally__c,
                Customer_Account__c = listOfTAReferrals[0].Referral__r.Customer__r.AccountId
            );
            ESAPI.securityUtils().validatedInsert(new List<Project__c>{newProject});
            listOfTAReferrals[0].Referral_Status__c = 'Converted';
            ESAPI.securityUtils().validatedUpdate(listOfTAReferrals);
        }
    }
}