src/objects/Specialty__c.object
<CustomObject>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trade_Ally_Specialty__c.object
<CustomObject>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Participating Programs</label>
        <referenceTo>Specialty__c</referenceTo>
        <relationshipLabel>Trade Ally Specialties</relationshipLabel>
        <relationshipName>Trade_Ally_Specialties</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Trade Ally Specialty</label>
    <nameField>
        <displayFormat>TAS-{000000}</displayFormat>
        <label>Trade Ally Specialty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Ally Specialties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WrappedInfoParserTest.cls
@IsTest
private class WrappedInfoParserTest {
	@IsTest
	static void testBehavior() {
		Account newAccount = new Account(
				Name = 'newAccount'
		);
		insert newAccount;
		String sObjectType = 'Specialty__c';
		String sObjectJunctionType = 'Trade_Ally_Specialty__c';
		Id tradeAllyId = newAccount.Id;
		String label = 'Participating Programs';
		String junctionFieldName = 'Specialty__c';
		FieldInfoWrapper newWrapper = new FieldInfoWrapper(
		 sObjectType,
		 sObjectJunctionType,
		 tradeAllyId,
		 label,
		 junctionFieldName
		);
		WrappedInfoParser.addItemToListOfSpecialFields(newWrapper);
		WrappedInfoParser.workWithSpesialFields();
        System.assertEquals(WrappedInfoParser.listOfSpecialFields.size(), 1);
	}
}